name: "Publish NPM Package"

on:
  workflow_call:
    inputs:
      enable_build:
        required: true
        type: boolean
    secrets:
      NPM_CI_TOKEN:
        required: true

jobs:
  publish_package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16']
    steps:
      # 1. Checkout github ref
      - uses: actions/checkout@v3

      # 2. Cache node modules
      - name: cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # 3. RUN build
      - name: build
        if: ${{ inputs.enable_build }}
        run: |
          npm i
          npm run build

      # 4. RUN publish
      - name: publish
        run: |
          echo -e "//npm.pkg.github.com/:_authToken=${NPM_CI_TOKEN} \n//registry.npmjs.org/:_authToken=${NPM_CI_TOKEN}" > .npmrc
          npm publish --access public
        env:
          NPM_CI_TOKEN: ${{ secrets.NPM_CI_TOKEN }}
